### PR TITLE
Remove compute_stresses_cart precompilation to fix ForwardDiff Dual tag ordering problems

### PR DESCRIPTION
**Pull request by Technici4n**
Workaround for https://github.com/JuliaDiff/ForwardDiff.jl/issues/714. The `precompilation_task.json` file is just `test/silicon_bands.json` without the postscf... I didn't give it more thought for now.

### CODE REVIEW

**Comment by Technici4n** [comment]
`compute_stresses_cart` still runs as a test, it's just that the precompilation now uses a different json file.

**Comment by mfherbst** [comment]
Oh sorry to be unclear. I thought to run the precompile json file as an extra test to ensure the json itself does not become out of date.

**Comment by Technici4n** [comment]
It already runs when precompiling AiidaDFTK at the beginning of the tests. Is that sufficient?

**Comment by mfherbst** [comment]
True, let's hope that work.

**Pull request merged**
